### ISSUE TITLE
Your Tool destroys my .NET 2.0 exe files

### ISSUE THREAD

**Issue by jayjupdhig** [brantburnett/NetCompressor#1]
Hello

Your Tool destroys my .NET 2.0 exe files. Interested for closer details? I can send it (before/after) via mail to you. just give me your address...

Regards, J

**Comment by brantburnett** [comment]
@martijintro I am no longer maintaining this tool, as there are a lot of better alternatives for modern applications and I don't use it anymore. However, feel free to fork this repo and make changes.

**Comment by jayjupdhig** [comment]
ok
